void allocateBuffers(struct dataStruct *st);
void cleanUpBuffers(struct dataStruct *st);
void doCrypt(FILE *inFile, FILE *outFile, uint64_t fileSize, struct dataStruct *st);
uint64_t freadWErrCheck(void *ptr, size_t size, size_t nmemb, FILE *stream, struct dataStruct *st);
uint64_t fwriteWErrCheck(void *ptr, size_t size, size_t nmemb, FILE *stream, struct dataStruct *st);
void genHMAC(FILE *dataFile, uint64_t fileSize, struct dataStruct *st);
void genHMACKey(struct dataStruct *st);
void genPassTag(struct dataStruct *st);
void genEvpSalt(struct dataStruct *st);
void genEvpKey(struct dataStruct *st);
void HKDFKeyFile(struct dataStruct *st);
void genKeyFileHash(FILE *dataFile, uint64_t fileSize, struct dataStruct *st);
uint64_t getFileSize(const char *filename);
uint8_t printSyntax(char *arg);
void signalHandler(int signum);
void makeMultipleOf(size_t *numberToChange, size_t multiple);
int workThread(char action, struct dataStruct *st);
void parseOptions(int argc, char *argv[], struct dataStruct *st);
void bytesPrefixed(char *prefixedString, unsigned long long bytes);
size_t getBufSizeMultiple(char *value);
void encListCallback(const OBJ_NAME *obj, void *arg);
void mdListCallback(const OBJ_NAME *obj, void *arg);
